import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { Hero } from '../components/Hero'
import { NavBar } from '../components/NavBar'
import { SearchBar } from '../components/SearchBar'

const Home: NextPage = () => {

  const [active, setActive] = useState(false);

  return (
    <div>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchBar active={active} />
      <NavBar active={active} setActive={setActive} />
      <Hero />

    </div>
  )
}

export default Home
